comfyfile_instances:
- token: your-token-here
  url: http://example.com:port
health_check:
  interval: 120
  timeout: 5
logging:
  debug: false
  retention_days: 7
  rotation_interval: 1
redis:
  db: 0
  host: localhost
  password: your-redis-password
  port: 6379
security:
  enabled: true
  secret: your-secret-key-here
server:
  host: "0.0.0.0"
  port: 8000
